Base Object & Protocol 구성
9in-team/GuinTeam-iOS pull request #2
Opened 2023-12-26 10:21 UTC by heonha

#### BaseViewController
- `disposeBag`: 이벤트 bag (미사용 할 수도 있으므로 lazy로 선언)
- `messageView`: 하단 메시지 알럿창 입니다.
- `setBackgroundColor`
    -  VC 초기화 후에 BackgroundColor 변경 필요시 사용합니다.
    - init 시에도 이 메서드로 backgroundColor를 결정합니다.
    - 기본값은 systemBackground 입니다.
- 키보드 내리기
    - `assignTextfieldHideKeyboardGesture()`: Gesture 를 `self.view`에 추가
    - `textFieldHideKeyboard()`: textfield가 firstresponder를 포기하도록 함

#### BaseViewController
- `disposeBag`: 이벤트 bag (미사용 할 수도 있으므로 lazy로 선언)
- `viewModel`: BaseViewModel을 상속하는 객체만 들어올 수 있음.
- `activityIndicator`: 로딩 인디케이터. lazy로 선언하여 미사용시 메모리에 올라가지않도록 구현
- `contentView`: UIView에 1개 계층 추가 구현. contentViewInset등 필요
- `setActivityIndicator()`: contentView에 `ActivityIndicatorView`를 추가하고의 `viewModel.isShowLoadingIndicator`의 상태를 구독합니다.

#### BaseViewModel
- `disposeBag`: 이벤트 bag (미사용 할 수도 있으므로 lazy로 선언)
- `isLoading`: 비동기 작업의 로딩 상태 이벤트를 방출합니다.

2023-12-26 14:31 UTC, heonha commented
- 프로토콜 다시 생성, BaseObject들에 Override 해서 사용
- 프리뷰 합치기
- 프리뷰 다크모드 확장.
- BaseView내 contentView 사용 재검토 
- input output pattern ( ViewModel ) 알아보기
- Alamofire REST 
- NavigationVC Push, Pop 등등 확장 생성

2023-12-30 06:49 UTC, heonha commented
회의 때 협의한 내용 작업 완료하였습니다!
리뷰 부탁드립니다. @cho1490

2024-01-01 09:46 UTC, cho1490 requested changes
코멘트에 한번에 정리해서 답글 남겨요 ㅎㅎ

ViewProtocol, ViewControllerProtocol 프로토콜에서 View 관련으로 공통된 부분(configure, layout) 이 있는데 하나로 분리하는것도 괜찮은거 같습니다. 어떻게 생각하시나요?!

ViewController 의 layout 메소드에서 addSubview 를 각각 UI 의 makeConstraints 를 사용하기 직전에 호출하게 되어있는데요! 
1번, 2번, 3번 총 3개의 UI 가 있을 때 2번이 3번에 접근해야할 때 혹시 문제가 될 수 있지 않을지 고민됩니다. addSubview 를 한 곳에서 먼저 호출하는 방법도 의견을 나누어 봐야될거 같아요 ㅎㅎ

MessageView, ActivityIndicatorView 에서 View 관련 프로토콜을 채택해서 같이 사용하면 좋을거 같아요!

Then 과 Snapkit 을 사용할 때 closure 내부에서 button, label 혹은 make 등등 반복해서 사용하는게 되는데 저는 first argument 를 의미하는 $0 을 즐겨 사용했습니다. 혹시 이렇게 사용하면 어떨까요 개인적으로 편하게 사용했습니다~!

2024-01-01 09:46 UTC, cho1490 commented on .swiftlint.yml
> +    error: 2 # 2글자 초과 시 에러
2글자 미만을 의미하는거 맞죠!?

2024-01-03 00:01 UTC, heonha commented on .swiftlint.yml
> +    error: 2 # 2글자 초과 시 에러
아 맞습니다 ^^; 반대로 기재했네요!

2024-01-03 00:18 UTC, heonha commented on .swiftlint.yml
> +    error: 2 # 2글자 초과 시 에러
> ViewProtocol, ViewControllerProtocol 프로토콜에서 View 관련으로 공통된 부분(configure, layout) 이 있는데 하나로 분리하는것도 괜찮은거 같습니다. 어떻게 생각하시나요?!

`configure()` : 해당 superview에 기본적으로 셋업 되어야 할 프로퍼티 설정 등 (레이아웃 외)
`layout()` : Layout 을 조정하는 코드만 작성 (SnapKit 코드 및 contentPriority 등)
위 목적 별로 작성해서 나누었는데 혹시 어떠신가요??

다른 내용은 오늘 틈틈이 확인 해보겠습니다!


> Then 과 Snapkit 을 사용할 때 closure 내부에서 button, label 혹은 make 등등 반복해서 사용하는게 되는데 저는 first argument 를 의미하는 $0 을 즐겨 사용했습니다. 혹시 이렇게 사용하면 어떨까요 개인적으로 편하게 사용했습니다.

네, 저는 snapkit 사용시 기본으로 `make in` 부분을 지우는게 번거로웠어서 저렇게 사용했었는데,
$0 으로 사용해도 좋을 것 같습니다 ㅎㅎ $0으로 진행하시죠! 더 깔끔하고 좋다고 생각합니다.


다른 부분은 오늘 틈틈이 확인해볼게요~

2024-01-03 00:19 UTC, heonha commented on .swiftlint.yml
> +    error: 2 # 2글자 초과 시 에러
> Then 과 Snapkit 을 사용할 때 closure 내부에서 button, label 혹은 make 등등 반복해서 사용하는게 되는데 저는 first argument 를 의미하는 $0 을 즐겨 사용했습니다. 혹시 이렇게 사용하면 어떨까요 개인적으로 편하게 사용했습니다.

네, 저는 snapkit 사용시 기본으로 `make in` 부분을 지우는게 번거로웠어서 저렇게 사용했었는데,
$0 으로 사용해도 좋을 것 같습니다 ㅎㅎ $0으로 진행하시죠! 더 깔끔하고 좋다고 생각합니다.


**다른 부분은 오늘 틈틈이 확인해볼게요~**

2024-01-04 23:55 UTC, heonha commented on .swiftlint.yml
> +    error: 2 # 2글자 초과 시 에러
> ViewProtocol, ViewControllerProtocol 프로토콜에서 View 관련으로 공통된 부분(configure, layout) 이 있는데 하나로 분리하는것도 괜찮은거 같습니다. 어떻게 생각하시나요?!

아, 이부분 잘못 이해 했네요 ㅎㅎ 
이 두가지 별도로 분리하는 것도 같은 목적이고 한곳에서 관리하게 되니 좋을 것 같습니다!
반영하도록 하겠습니다~

2024-01-05 00:02 UTC, heonha commented on .swiftlint.yml
> +    error: 2 # 2글자 초과 시 에러
> ViewController 의 layout 메소드에서 addSubview 를 각각 UI 의 makeConstraints 를 사용하기 직전에 호출하게 되어있는데요!
1번, 2번, 3번 총 3개의 UI 가 있을 때 2번이 3번에 접근해야할 때 혹시 문제가 될 수 있지 않을지 고민됩니다. addSubview 를 한 곳에서 먼저 호출하는 방법도 의견을 나누어 봐야될거 같아요 ㅎㅎ

네 이부분은 좀 더 논의해봐야 할 것 같아요 ㅎㅎ 
제생각엔 아래 처럼 layout() 메소드 상단에서 subview를 추가해주면
2번이 3번에 접근해야 하는 경우가 있을 때 문제가 발생하지 않을 것 같은데 어떠신가요?!

```swift
    override func layout() {
        super.layout()
        view.addSubview(label)
        view.addSubview(resultLabel)
        view.addSubview(button)

        layoutLabel()
        layoutResultLabel()
        layoutButton()
    }
    
    private func layoutLabel() {
        label.snp.makeConstraints { make in
            make.center.equalToSuperview()
            make.height.greaterThanOrEqualTo(40)
            make.width.greaterThanOrEqualTo(100)
        }
    }
    
    private func layoutResultLabel() {
        resultLabel.snp.makeConstraints { make in
            make.centerX.equalTo(label)
            make.top.equalTo(label.snp.bottom).offset(20)
            make.height.greaterThanOrEqualTo(40)
            make.width.greaterThanOrEqualTo(100)
        }
    }
    
    private func layoutButton() {
        button.snp.makeConstraints { make in
            make.centerX.equalTo(resultLabel)
            make.top.equalTo(resultLabel.snp.bottom).offset(20)
            make.height.greaterThanOrEqualTo(40)
            make.width.greaterThanOrEqualTo(100)
        }
    }
```

2024-01-05 00:25 UTC, heonha commented
검토 해주신 부분 우선 반영하여 재 검토 요청드립니다~

2024-01-06 10:00 UTC, cho1490 approved these changes
고생하셨습니다.

2024-01-07 06:31 UTC, merged